---
- name: 1
  command: "wget --header 'Cookie: oraclelicense=accept-securebackup-cookie' https://download.oracle.com/otn-pub/java/jdk/11.0.1+13/90cf5d8f270a4347a95050320eef3fb7/jdk-11.0.1_linux-x64_bin.tar.gz"
  when:
    - ansible_distribution == 'Debian'
  become: yes
  become_method: sudo
  become_user: root

