---
- include_tasks: ../../../roles/splunk_common/tasks/wait_for_splunk_instance.yml
  vars:
    splunk_instance_address: "{{ splunk.multisite_master }}"

- name: Convert Extrenal Cluster Master Name into Internal URI
  set_fact:
      multisite_master_uri: "https://{{ splunk.multisite_master }}:{{ splunk.multisite_master_port }}"

- name: Set the multisite master
  command: "{{ splunk.exec }} edit cluster-config -mode master -multisite true -available_sites {{splunk.all_sites}} -site {{splunk.site}} -site_replication_factor origin:{{splunk.multisite_repilcation_factor_origin}},total:{{splunk.multisite_repilcation_factor_total}} -site_search_factor origin:{{splunk.multisite_search_factor_origin}},total:{{splunk.multisite_search_factor_total}} -auth admin:{{splunk.admin_pw}}"
  become: yes
  become_user: "{{ splunk.user }}"
  register: set_multisite_master
  until: set_multisite_master.rc == 0
  changed_when: set_multisite_master.rc == 0
  retries: "{{ retry_num }}"
  delay: 3
  ignore_errors: yes
  notify:
    - Restart the splunkd service
  no_log: "{{ hide_password }}"
