---
- name: Run Default Installation Plays
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Checking for Pre-installation Ansible Tasks
      include_tasks: "{{lookup('first_found', ansible_pre_tasks)}}"
      when:
        - ansible_pre_tasks is defined
        - ansible_pre_tasks is not none
    - name: Upgrade role
      include_role:
        name: "splunk_upgrade"
      when:
        - splunk.upgrade is defined
        - splunk.upgrade

    - name: Provision role
      include_role:
        name: "{{ splunk.role }}"
      when:
        - splunk.role is defined
        - splunk.role != 'splunk_search_head_captain'
        - not splunk.upgrade

    # Special case for search head captain
    - name: Provision role
      include_role:
        name: "splunk_search_head"
      when:
        - splunk.role is defined
        - splunk.role == 'splunk_search_head_captain'
        - not splunk.upgrade
    - name: Checking for Post-installation Ansible Tasks
      include_tasks: "{{lookup('first_found', ansible_post_tasks)}}"
      when:
        - ansible_post_tasks is defined
        - ansible_post_tasks is not none

