---
- name: Execute pre splunk start commands
  command: "{{splunk.exec}} {{ item }}"
  become: yes
  become_user: "{{ splunk.user }}"
  with_items: "{{ splunk.before_start_cmd }}"
  register: task_result
  until: task_result.rc == 0 or "already exists" in task_result.stderr
  retries: "{{ retry_num }}"
  delay: "{{ delay_num }}"
  when: splunk.before_start_cmd is defined
  ignore_errors: true
