---
- name: Stat ta-dockerlogs_fileinput
  stat: path=/tmp/ta-dockerlogs_fileinput.tar.gz
  register: dockerlogs_fileinput_status

- name: Install ta-dockerlogs_fileinput
  unarchive:
    src: /tmp/ta-dockerlogs_fileinput.tar.gz
    dest: "{{ splunk.app_paths.default }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
  when: dockerlogs_fileinput_status.stat.exists

- name: Stat ta-dockerstats
  stat: path=/tmp/ta-dockerstats.tar.gz
  register: dockerstats_status

- name: Install ta-dockerstats
  unarchive:
    src: /tmp/ta-dockerstats.tar.gz
    dest: "{{ splunk.app_paths.default }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
  when: dockerstats_status.stat.exists

- name: Download Docker community edition
  command: "wget -qO {{ splunk.app_paths.default }}/ta-dockerstats/bin/docker-{{ docker_version }}-ce.tgz https://download.docker.com/linux/static/stable/{{ ansible_architecture }}/docker-{{ docker_version }}-ce.tgz"
  ignore_errors: true

- name: Create a tmp directory
  file:
    path: "{{ splunk.app_paths.default }}/ta-dockerstats/bin/tmp"
    state: directory
  ignore_errors: true

- name: Untar docker binary to apps tmp
  command: "tar xzvf {{ splunk.app_paths.default }}/ta-dockerstats/bin/docker-{{ docker_version }}-ce.tgz -C {{ splunk.app_paths.default }}/ta-dockerstats/bin/tmp"
  ignore_errors: true

- name: Remove downloaded binary
  file:
    path: "{{ splunk.app_paths.default }}/ta-dockerstats/bin/docker-{{ docker_version }}-ce.tgz"
    state: absent
  ignore_errors: true

# must use shell module for globing
- name: Copy from tmp directory to apps bin
  shell: "mv {{ splunk.app_paths.default }}/ta-dockerstats/bin/tmp/docker/* {{ splunk.app_paths.default }}/ta-dockerstats/bin"

- name: Make files executable
  command: "chmod +x {{ splunk.app_paths.default }}/ta-dockerstats/bin/docker"

# must use shell module for globing
- shell: "chown {{ splunk.user }}:{{ splunk.group }} {{ splunk.app_paths.default }}/ta-dockerstats/bin/*.sh"

- command: "chown {{ splunk.user }}:{{ splunk.group }} {{ splunk.app_paths.default }}/ta-dockerstats/bin/docker"

- name: Update permissions on /var/run/docker.sock
  file:
    path: /var/run/docker.sock
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
  become: yes
