version: 2
jobs:
  splunk-ansible-test:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Setup tests
          command: |
            make test_setup
      - run:
          name: Lint playbooks
          command: |
            make lint

workflows:
  version: 2
  run_tests:
    jobs:
      - splunk-ansible-test
