version: 2
jobs:
  splunk-ansible-test:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Lint playbooks
          command: |
            make lint
      - run:
          name: Run small tests
          command: |
            make small-tests
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results

workflows:
  version: 2
  run_tests:
    jobs:
      - splunk-ansible-test
