---
- include_tasks: ../../../roles/splunk_common/tasks/enable_forwarding.yml

- name: Set deployer SHC key and label
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/server.conf"
    section: shclustering
    option: "{{ item.opt }}"
    value: "{{ item.val }}"
  with_items:
    - { opt: 'pass4SymmKey', val: '{{ splunk.shc.secret }}' }
    - { opt: 'shcluster_label', val: '{{ splunk.shc.label }}' }
  loop_control:
    label: "{{ item.opt }}"
  become: yes
  become_user: "{{ splunk.user }}"
  no_log: "{{ hide_password }}"
  notify:
    - Restart the splunkd service

- name: Flush restart handlers
  meta: flush_handlers

- include_tasks: ../../../roles/splunk_common/tasks/provision_apps.yml
  when:
    - splunk.apps_location

- include_tasks: push_apps_to_search_heads.yml
  when:
    - splunk.apps_location
