---
- include_tasks: ../../splunk_common/tasks/stop_splunk.yml
- include_tasks: ../../splunk_common/tasks/install_splunk.yml

- name: Generate user-seed.conf
  ini_file:
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    dest: "{{ splunk.home }}/etc/system/local/user-seed.conf"
    section: user_info
    option: "{{ item.opt }}"
    value: "{{ item.val }}"
  with_items:
    - { opt: 'USERNAME', val: 'admin' }
    - { opt: 'PASSWORD', val: '{{ splunk.password }}' }
  loop_control:
    label: "{{ item.opt }}"
  no_log: "{{ hide_password }}"

- include_tasks: ../../splunk_common/tasks/start_splunk.yml
- include_tasks: ../../splunk_common/tasks/add_splunk_license.yml