---
- name: Install Splunk
  unarchive:
    src: "{{ splunk.build_location }}"
    dest: "{{ splunk.opt }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    remote_src: "{{ splunk.build_remote_src }}"

- name: Generate user-seed.conf
  ini_file:
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    dest: "{{ splunk.home }}/etc/system/local/user-seed.conf"
    section: user_info
    option: "{{ item.opt }}"
    value: "{{ item.val }}"
  with_items:
    - { opt: 'USERNAME', val: 'admin' }
    - { opt: 'PASSWORD', val: '{{ splunk.password }}' }
  loop_control:
    label: "{{ item.opt }}"
  no_log: "{{ hide_password }}"

- name: Start Splunk
  command: "{{ splunk.exec }} start --accept-license --answer-yes --no-prompt"
  become: yes
  become_user: "{{ splunk.user }}"
