---
- name: Download Splunk license
  get_url:
    url: "{{ splunk.license_uri }}"
    dest: "{{ splunk.license_download_dest }}"
    timeout: 20
  when:
    - splunk.role == "splunk_license_master" or not splunk.license_master_included
  register: downloaded_license_path
  ignore_errors: yes
  until: downloaded_license_path is success
  retries: 5
  delay: 3

- name: Apply Splunk license
  command: "{{ splunk.exec }} add licenses {{lookup('first_found', license_locations)}} -auth admin:{{ splunk.password }}"
  become: yes
  become_user: "{{ splunk.user }}"
  when:
    - not (splunk.ignore_license | bool)
    - splunk.role == "splunk_license_master" or not splunk.license_master_included
  ignore_errors: true
  vars:
    license_locations:
      - "{{ splunk.license_download_dest }}"
      - "{{ splunk.nfr_license }}"
  notify:
    - Restart the splunkd service

- name: Set as license slave
  include_tasks: set_as_license_slave.yml
  vars:
    license_master_host: "{{ groups.splunk_license_master[0] }}"
  when:
    - splunk.license_master_included | bool
    - splunk.role != "splunk_license_master"

- name: Flush handlers
  meta: flush_handlers
