---
- name: Install generic Splunk app
  uri:
    url: "https://127.0.0.1:{{ splunk.svc_port }}/services/apps/local"
    method: POST
    user: admin
    password: "{{ splunk.password }}"
    validate_certs: false
    body: "name={{ app_url | urlencode() }}&update=true&filename=true"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: [ 200, 201 ]
    timeout: 300
  when:
    - "'splunkbase.splunk.com' not in app_url"

- name: Install Splunkbase app
  uri:
    url: "https://127.0.0.1:{{ splunk.svc_port }}/services/apps/local"
    method: POST
    user: admin
    password: "{{ splunk.password }}"
    validate_certs: false
    body: "name={{ app_url | urlencode() }}&update=true&filename=true&auth={{ splunkbase_token }}"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: [ 200, 201 ]
    timeout: 300
  when:
    - "'splunkbase.splunk.com' in app_url"
    - splunkbase_token is defined
    - splunkbase_token != None
