---
- name: Install Local Splunk Apps
  command: "{{ splunk.exec }} install app {{ item }} -auth admin:{{ splunk.password }}"
  with_items:
    - "{{ splunk.local_apps_location }}"
  no_log: "{{ hide_password }}"
  notify:
    - Restart the splunkd service