---
- name: Install Splunkbase app
  uri:
    url: "https://127.0.0.1:{{ splunk.svc_port }}/services/apps/local"
    method: POST
    user: admin
    password: "{{ splunk.password }}"
    validate_certs: false
    body: "name={{ app_url | urlencode() }}&update=true&filename=true&auth={{ splunkbase_token }}"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    status_code: [ 200, 201 ]
    timeout: 300
  when:
    - "'splunkbase.splunk.com' in app_url"
    - splunkbase_token is defined
    - splunkbase_token != None
  no_log: "{{ hide_password }}"

- name: Download generic Splunk app
  get_url:
    url: "{{ app_url }}"
    dest: /tmp/app.spl
    mode: 0777
  register: 
  when:
    - "'splunkbase.splunk.com' not in app_url"
    - app_url is search("http")
  ignore_errors: true

# Some premium apps require installation via untar command, instead of the traditionally-accepted app installation means (example below):
# command: "{{ splunk.exec }} install app {% if 'http' in app_url %}/tmp/app.spl{% else %}{{ app_url }}{% endif %} -auth admin:{{ splunk.password }}"
- name: Install generic Splunk app
  unarchive:
    src: "{% if 'http' in app_url %}/tmp/app.spl{% else %}{{ app_url }}{% endif %}"
    dest: "{{ splunk.app_paths.default }}"
    remote_src: true
  become: yes
  become_user: "{{ splunk.user }}"
  ignore_errors: true
  no_log: "{{ hide_password }}"
  notify:
    - Restart the splunkd service

- name: Remove downloaded app
  file:
    dest: /tmp/app.spl
    state: absent
  when:
    - '"/tmp/app.spl" is file'
  ignore_errors: true
