---
- name: Install Splunk
  unarchive:
    src: "{{ splunk.build_location }}"
    dest: "{{ splunk.opt }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    remote_src: "{{ splunk.build_remote_src }}"
  when: ansible_system is match("Linux")

- name: Install Splunk (Windows)
  command: "msiexec /I {{ splunk.build_location }} AGREETOLICENSE=yes LAUNCHSPLUNK=0 INSTALLDIR=C:\\\\opt\\\\splunk /passive /qn"
  when: ansible_system is match("CYGWIN*|Win32NT")

- name: Remove installer
  file:
    dest: "{{ splunk.build_location }}"
    state: "absent"
  ignore_errors: yes
