---
- include_tasks: change_splunk_directory_owner.yml
  when:
    - splunk_home_ownership_enforcement is defined
    - splunk_home_ownership_enforcement | bool
  
- include_tasks: get_facts.yml

- include_tasks: update_etc.yml

- include_tasks: install_splunk.yml
  when:
    - first_run is defined
    - first_run | bool
    - "'build_location' in splunk and splunk.build_location is not none"

- include_tasks: remove_first_login.yml
  when:
    - first_run is defined
    - first_run | bool

- include_tasks: install_java.yml
  when:
    - java_version is defined

# This needs to be done before any encrypted passkeys are generated
- include_tasks: set_splunk_secret.yml
  when:
    - first_run is defined
    - first_run | bool

- include_tasks: set_user_seed.yml
  when:
    - first_run is defined
    - first_run | bool

- include_tasks: pre_splunk_start_commands.yml
  ignore_errors: true
  
- include_tasks: enable_s2s_port.yml
  when:
    - "'s2s_enable' in splunk and splunk.s2s_enable is not none"
    - splunk.s2s_enable | bool
    - first_run is defined
    - first_run | bool

- include_tasks: enable_service.yml
  when: splunk.enable_service and ansible_system is match("Linux")

- include_tasks: enable_ssl_on_gui.yml
  when:
    - "'http_enableSSL' in splunk and splunk.http_enableSSL is not none"
    - splunk.http_enableSSL | bool
    - first_run is defined
    - first_run | bool

- include_tasks: set_any_generic_config.yml
  when:
    - "'conf' in splunk"

- include_tasks: start_splunk.yml

- include_tasks: clean_user_seed.yml
  when:
    - first_run is defined
    - first_run | bool

- include_tasks: add_splunk_license.yml
  when:
    - first_run is defined
    - first_run | bool
