---
- include_tasks: change_splunk_directory_owner.yml
  when:
    - splunk_home_ownership_enforcement is defined
    - splunk_home_ownership_enforcement | bool

- include_tasks: check_first_run.yml

- include_tasks: install_splunk.yml
  when:
    - first_run is defined
    - first_run | bool

- include_tasks: set_user_seed.yml
  when:
    - first_run is defined
    - first_run | bool

- include_tasks: enable_s2s_port.yml
  when:
    - splunk.s2s_enable is defined
    - splunk.s2s_enable | bool

- include_tasks: enable_service.yml
  when: splunk.enable_service and ansible_system is match("Linux")

- include_tasks: set_splunk_secret.yml
  when:
    - splunk.secret is defined
    - splunk.secret

- include_tasks: enable_ssl_on_gui.yml
  when:
    - splunk.http_enableSSL is defined
    - splunk.http_enableSSL | bool

- include_tasks: set_any_generic_config.yml
  when:
    - "'conf' in splunk"

- include_tasks: start_splunk.yml

- include_tasks: clean_user_seed.yml

- include_tasks: add_splunk_license.yml

- include_tasks: install_app.yml
  vars:
    app_url: "{{ item }}"
  loop: "{{ splunk.apps_location }}"
