---
- include_tasks: check_first_run.yml

- include_tasks: install_splunk.yml
  when:
    - first_run is defined
    - first_run | bool

- include_tasks: set_user_seed.yml
  when:
    - first_run is defined
    - first_run | bool

- include_tasks: enable_s2s_port.yml

- include_tasks: enable_service.yml
  when: splunk.enable_service and ansible_system is match("Linux")

- include_tasks: set_splunk_secret.yml
  when:
    - splunk.secret is defined
    - splunk.secret

- include_tasks: start_splunk.yml

- include_tasks: clean_user_seed.yml

- include_tasks: add_splunk_license.yml
  when:
    - first_run is defined
    - first_run | bool

- include_tasks: install_app.yml
  vars:
    app_url: "{{ item }}"
  loop: "{{ splunk.apps_location }}"
