---
- include_tasks: set_config_file.yml
  vars:
    conf_file: "{{ item.key }}.conf"
    conf_directory: "{% if item.value.directory is defined %}{{ item.value.directory }}{% else %}{{ splunk.home }}/etc/system/local{% endif %}"
    conf_stanzas: "{{ item.value.content }}"
  when:
    - (item.value | length > 0)
  with_dict: "{{ splunk.conf }}"
