---
- name: Generate user-seed.conf
  ini_file:
    dest: "{{ splunk.home }}/etc/system/local/user-seed.conf"
    section: user_info
    option: "{{ item.opt }}"
    value: "{{ item.val }}"
  with_items:
    - { opt: 'USERNAME', val: 'admin' }
    - { opt: 'PASSWORD', val: '{{ splunk.password }}' }
  loop_control:
    label: "{{ item.opt }}"
