---
- include_tasks: ../../../roles/splunk_common/tasks/set_as_hec_receiver.yml
  when:
    - not splunk.hec_disabled | bool
    - splunk.hec_token is defined and splunk.hec_token != None

- include_tasks: ../../../roles/splunk_common/tasks/add_forward_server.yml
  vars:
    role: splunk_indexer

- include_tasks: ../../../roles/splunk_common/tasks/add_forward_server.yml
  vars:
    role: splunk_standalone
