---
- include_tasks: search_head_clustering.yml
  when:
    - splunk.search_head_cluster
    - splunk.deployer_included

## Indexer Clustering Scenario
- include_tasks: peer_cluster_master.yml
  when:
    - splunk.indexer_cluster

## Non Indexer Clustering Scenario
- include_tasks: peer_indexers.yml
  when:
    - not splunk.indexer_cluster

- include_tasks: ../../../roles/splunk_common/tasks/enable_forwarding.yml

- include_tasks: ../../../roles/splunk_common/tasks/provision_apps.yml
  when:
    - splunk.apps_location
    - not splunk.search_head_cluster

- include_tasks: ../../../roles/splunk_common/tasks/check_for_required_restarts.yml
